import './globals.css'
import { Montserrat } from 'next/font/google'

import Navigation from '../components/ui/Navigation'
import Footer from '@/components/ui/Footer'
import FooterDeveloper from '@/components/ui/FooterDeveloper'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const montserrat = Montserrat({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <body className='relative'>
        <Navigation />

        {children}

        <Footer />

        <FooterDeveloper />
      </body>
    </html>
  )
}
