version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
        - POSTGRES_DB=ministoredb
        - POSTGRES_USER=ministore
        - POSTGRES_PASSWORD=ministorepass
    ports:
      - 5433:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ministore.com
      - PGADMIN_DEFAULT_PASSWORD=ministorepass
    ports:
      - 5050:80